### ISSUE TITLE
How to use speaker_name instead of speaker_audio_file

### ISSUE THREAD

**Issue by siraphopp** [anhnh2002/XTTSv2-Finetuning-for-New-Languages#31]
Following your inference code,

```
# Inference
tts_text = "Good to see you."
speaker_audio_file = "ref.wav"
lang = "vi"

gpt_cond_latent, speaker_embedding = XTTS_MODEL.get_conditioning_latents(
    audio_path=speaker_audio_file,
    gpt_cond_len=XTTS_MODEL.config.gpt_cond_len,
    max_ref_length=XTTS_MODEL.config.max_ref_len,
    sound_norm_refs=XTTS_MODEL.config.sound_norm_refs,
)
```

I have finetuned the model with my dataset using speaker_name @actor001. Can I use @actor001 instead of speaker_audio_file? If it can, how to do it?

**Comment by anhnh2002** [comment]
No, you cannot directly use @actor001 as a speaker identifier instead of speaker_audio_file in the current version. For now, you'll need to use one of your training audio samples from @actor001 as the reference audio file.

As a workaround, you can use any audio file from your training dataset that corresponds to @actor001 as the speaker_audio_file.

This feature (using speaker identifiers directly) will be implemented in a future update. You can track the progress in upcoming releases.
